#!/usr/bin/env bash
# Bu skript /etc/passwd faylını oxuyur və istifadəçi adı, UID və ev qovluğunu çıxarır

while IFS=: read -r username _ uid _ _ home _; do
    echo "$username:$uid:$home"
done < /etc/passwd

