#!/usr/bin/env bash
# /etc/passwd faylının məzmununu while + IFS ilə oxuyur və formatlanmış məlumat verir

while IFS=: read -r username password userid groupid gecici home shell
do
    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $gecici"
done < /etc/passwd
