#!/usr/bin/env bash
# Bu skript 1-dən 20-ə qədər olan rəqəmləri göstərir və bəzi xüsusi hallarda superstition mesajları verir.

count=1
while [ $count -le 20 ]
do
  case $count in
    4)
      echo "$count"
      echo "bad luck from China"
      ;;
    9)
      echo "$count"
      echo "bad luck from Japan"
      ;;
    17)
      echo "$count"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$count"
      ;;
  esac
  ((count++))
done
