#!/usr/bin/env bash
# Stop 4-to_infinity_and_beyond process without kill or killall using pgrep

pid=$(ps aux | grep '4-to_infinity_and_beyond' | grep -v grep | awk '{print $2}')

if [[ -n $pid ]]; then
    builtin kill "$pid"
fi

