#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process without using kill or killall

pids=$(pgrep -f 4-to_infinity_and_beyond)

for pid in $pids; do
  # Send SIGTERM (signal 15) to each PID using perl
  perl -e "kill 15, $pid"
done



